#!/bin/bash
# Script to add YAML front matter to documentation files
# Generated by Metadata Implementer Agent

# Feature docs front matter mappings
declare -A FEATURE_DOCS

FEATURE_DOCS["accessibility-improvements.md"]="---
title: Accessibility Improvements WCAG 2.1 Level AA
description: Comprehensive WCAG 2.1 Level AA accessibility implementation including ARIA landmarks, keyboard navigation, and screen reader support
category: reference
tags: [accessibility, pwa, components]
difficulty: intermediate
---"

FEATURE_DOCS["channel-stats-usage.md"]="---
title: Channel Statistics Usage Guide
description: Guide to using the channel statistics feature for viewing member counts, message activity, and channel analytics
category: howto
tags: [channels, components]
difficulty: beginner
---"

FEATURE_DOCS["drafts-implementation.md"]="---
title: Message Drafts Implementation
description: Implementation of persistent message drafts with autosave functionality and local storage integration
category: reference
tags: [chat, stores, components]
difficulty: intermediate
---"

FEATURE_DOCS["export-implementation.md"]="---
title: Data Export Implementation
description: Complete data export functionality for exporting messages, profiles, and channel data in JSON format
category: reference
tags: [chat, components, privacy]
difficulty: intermediate
---"

FEATURE_DOCS["icon-integration-guide.md"]="---
title: Icon Integration Guide
description: Guide for integrating and using icons across the Nostr-BBS application
category: howto
tags: [components, pwa]
difficulty: beginner
---"

FEATURE_DOCS["link-preview-implementation.md"]="---
title: Link Preview Implementation
description: Implementation of URL link previews with metadata extraction and OpenGraph protocol support
category: reference
tags: [chat, components, api]
difficulty: intermediate
---"

FEATURE_DOCS["mute-implementation-summary.md"]="---
title: Mute and Block User Implementation Summary
description: Complete implementation guide for user muting and blocking functionality with local storage persistence
category: reference
tags: [chat, privacy, stores]
difficulty: intermediate
---"

FEATURE_DOCS["mute-quick-reference.md"]="---
title: Mute Feature Quick Reference
description: Quick reference guide for using the mute and block user features
category: howto
tags: [chat, privacy]
difficulty: beginner
---"

FEATURE_DOCS["nip-25-reactions-implementation.md"]="---
title: NIP-25 Reactions Implementation
description: Implementation of emoji reactions to messages using NIP-25 protocol specification
category: reference
tags: [nip-25, reactions, nostr-protocol]
difficulty: intermediate
---"

FEATURE_DOCS["notification-system-phase1.md"]="---
title: Notification System Phase 1 Implementation
description: Initial phase implementation of the notification system with browser notifications and service worker integration
category: reference
tags: [notifications, pwa, components]
difficulty: advanced
---"

FEATURE_DOCS["pinned-messages-implementation.md"]="---
title: Pinned Messages Implementation
description: Implementation of message pinning functionality for highlighting important channel messages
category: reference
tags: [chat, channels, components]
difficulty: intermediate
---"

FEATURE_DOCS["pwa-implementation.md"]="---
title: Progressive Web App Implementation
description: Complete PWA implementation including service worker, offline support, and app installation
category: reference
tags: [pwa, deployment, serverless]
difficulty: advanced
---"

FEATURE_DOCS["pwa-quick-start.md"]="---
title: PWA Quick Start Guide
description: Quick start guide for installing and using Nostr-BBS as a Progressive Web App
category: tutorial
tags: [pwa, deployment]
difficulty: beginner
---"

FEATURE_DOCS["search-implementation.md"]="---
title: Channel Message Search Implementation
description: Implementation of channel message search with filtering, highlighting, and advanced search options
category: reference
tags: [search, chat, components]
difficulty: intermediate
---"

FEATURE_DOCS["search-implementation-summary.md"]="---
title: Search Implementation Summary
description: Summary of both keyword search and semantic search implementations in Nostr-BBS
category: explanation
tags: [search, semantic-search, components]
difficulty: intermediate
---"

FEATURE_DOCS["search-usage-guide.md"]="---
title: Semantic Search Usage Guide
description: User guide for using the AI-powered semantic search feature to find messages by meaning
category: howto
tags: [semantic-search, search]
difficulty: beginner
---"

FEATURE_DOCS["threading-implementation.md"]="---
title: Quote/Reply Threading Implementation
description: Implementation of message threading with quote and reply functionality using NIP-10 tags
category: reference
tags: [threading, chat, components, nostr-protocol]
difficulty: advanced
---"

FEATURE_DOCS["threading-quick-reference.md"]="---
title: Threading Feature Quick Reference
description: Quick reference guide for using message threading, quoting, and reply features
category: howto
tags: [threading, chat]
difficulty: beginner
---"

echo "Feature documentation front matter mappings created successfully"
echo "Total feature docs: ${#FEATURE_DOCS[@]}"
